# Generated by Django 5.0.3 on 2024-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(blank=True, max_length=50, null=True)),
                ('dhead', models.CharField(blank=True, max_length=50, null=True)),
                ('dtime', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
